name: Check Free Games

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # อัปเดตเป็น v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }} # ใช้ Token ที่เราเพิ่งสร้าง
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install discord.py requests beautifulsoup4

      - name: Run bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          RAWG_API_KEY: ${{ secrets.RAWG_API_KEY }} # ต้องมีบรรทัดนี้บอทถึงจะดึง Genre ได้
        run: python main.py

      - name: Commit and Push History
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sent_games.txt
          git commit -m "Update sent games history [skip ci]" || exit 0
          git push origin main
