name: Check Free Games

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # อนุญาตให้เขียนข้อมูลลงใน Repo ได้

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          fetch-depth: 0 # ดึงประวัติทั้งหมดเพื่อป้องกันการชนกันของไฟล์

      - name: Run bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          RAWG_API_KEY: ${{ secrets.RAWG_API_KEY }}
        run: python main.py

      - name: Commit and Push History
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # ขั้นตอนสำคัญ: รวมไฟล์ประวัติจาก GitHub เข้ากับไฟล์ที่บอทเพิ่งเขียน
          git add sent_games.txt
          git stash # เก็บไฟล์ที่บอทเขียนไว้ชั่วคราว
          git pull origin main --rebase # ดึงข้อมูลล่าสุดจาก GitHub มาวางรอ
          git stash pop # เอาข้อมูลที่บอทเขียนไปวางทับ/ต่อท้าย
          
          git add sent_games.txt
          git commit -m "Update history [skip ci]" || exit 0
          git push origin main
          
